import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const workSans = localFont({
  src: [
    {
      path: '../../public/static/fonts/WorkSans/WorkSans-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/WorkSans/WorkSans-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/WorkSans/WorkSans-Medium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/WorkSans/WorkSans-SemiBold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/WorkSans/WorkSans-Bold.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/WorkSans/WorkSans-LightItalic.woff',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../../public/static/fonts/WorkSans/WorkSans-Italic.woff',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/static/fonts/WorkSans/WorkSans-BoldItalic.woff',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-worksans'
});

const clash = localFont({
  src: [
    {
      path: '../../public/static/fonts/ClashDisplay/ClashDisplay-Extralight.woff',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/ClashDisplay/ClashDisplay-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/ClashDisplay/ClashDisplay-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/ClashDisplay/ClashDisplay-Medium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/ClashDisplay/ClashDisplay-Semibold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/static/fonts/ClashDisplay/ClashDisplay-Bold.woff',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-clash'
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${workSans.variable} ${clash.variable}`}>
      <body className="antialiased font-worksans">
        {children}
      </body>
    </html>
  );
}
